services:
  tftp:
    image: pghalliday/tftp@sha256:59f843a93d62ac6e2fa475ee3d1a3786464fe5ea0334e6f1ea79bdec837f09fa
    command:
      - --foreground
      - --secure
      - /var/tftpboot
    volumes:
      - type: bind
        source: ./data
        target: /var/tftpboot
    network_mode: host  # Allows TFTP data transfers on 127.0.0.1.
